# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
#   _                        _             _
#  (_) __ ___   ____ _ _ __ (_)_   _ _ __ (_)_   _
#  | |/ _` \ \ / / _` | '_ \| | | | | '_ \| | | | |
#  | | (_| |\ V / (_| | | | | | |_| | | | | | |_| |
# _/ |\__,_| \_/ \__,_|_| |_|_|\__,_|_| |_|_|\__,_|
#|__/==============================================
#





## => Site Settings
##############################
text_skin: default # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
highlight_theme: default # "default" (default), "tomorrow", "tomorrow-night", "tomorrow-night-eighties", "tomorrow-night-blue", "tomorrow-night-bright"
url     : javaniuniu.com # the base hostname & protocol for your site e.g. https://www.someone.com
baseurl : # does not include hostname
title   : JAVA 牛牛
description: > # this means to ignore newlines until "Language & timezone"
  主要是想看下自己还能在多做些什么


## => Language and Timezone
##############################
lang: en # the language of your site, default as "en"
timezone: Asia/Shanghai # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values


## => Author and Social
##############################
author:
  type      : person # "person" (default), "organization"
  name      : java牛牛
  url       : javaniuniu.com
  avatar    : favicon.ico # path or url of avatar image (square)
  bio       : >
        I am an amazing person.
  email     : king101125s@gmail.com
  facebook  : minplemon # "user_name" the last part of your profile url, e.g. https://www.facebook.com/user_name
  twitter   : minplemon # "user_name" the last part of your profile url, e.g. https://twitter.com/user_name
  weibo     : # "user_id"   the last part of your profile url, e.g. https://www.weibo.com/user_id/profile?...
  googleplus: # "user_id"   the last part of your profile url, e.g. https://plus.google.com/u/0/user_id
  telegram  : # "user_name" the last part of your profile url, e.g. https://t.me/user_name
  medium    : # "user_name" the last part of your profile url, e.g. https://medium.com/user_name
  zhihu     : # "user_name" the last part of your profile url, e.g. https://www.zhihu.com/people/user_name
  douban    : # "user_name" the last part of your profile url, e.g. https://www.douban.com/people/user_name
  linkedin  : # "user_name" the last part of your profile url, e.g. https://www.linkedin.com/in/user_name
  github    : javaniuniu # "user_name" the last part of your profile url, e.g. https://github.com/user_name
  npm       : # "user_name" the last part of your profile url, e.g. https://www.npmjs.com/~user_name



## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: javaniuniu/javaniuniu.github.io
repository_tree: master


## => Paths
##############################
paths:
  root    : # title link url, "/" (default)
  home    : /home/ # home layout url, "/" (default)
  archive : # "/archive.html" (default)
  rss     : # "/feed.xml" (default)


## => Post
##############################
## excerpt
excerpt_separator: <!--more-->

## license
license: CC-BY-4.0 # "CC-BY-4.0", "CC-BY-SA-4.0", "CC-BY-NC-4.0", "CC-BY-ND-4.0"

## TOC
toc:
  selectors: "h1,h2,h3,h4,h5,h6" # "h1,h2,h3" (default)


## => Markdown Enhancements
##############################
## Mathjax
mathjax: true # false (default), true
mathjax_autoNumber: true # false (default), true

## Mermaid
mermaid: true # false (default), true

## Chart
chart: true # false (default), true


## => Paginate
##############################
paginate: 8
paginate_path: /home/page:num # don't change this unless for special need


## => Sources
##############################
sources: # bootcdn (default), unpkg


## => Sharing
##############################
sharing:
  provider: addtoany # false (default), "addtoany", "addthis", "custom"

  ## AddThis
  addthis:
    id: # AddThis pubid, e.g. ra-5xxxxxxxxxxx


## => Comments
##############################
comments:
  provider: gitalk # false (default), "disqus", "gitalk", "valine", "custom"

  ## Disqus
  disqus:
    shortname: #javaniuniu # the Disqus shortname for the site

  ## Gitalk
  # please refer to https://github.com/gitalk/gitalk for more info.
  gitalk:
    clientID    : '9d27fc6cf6f99bad887f' # GitHub Application Client ID
    clientSecret: '11102eaecc1e9ccb50b532367bfa4ab10973735d' # GitHub Application Client Secret
    repository  : 'javaniuniu.github.io' # GitHub repo
    owner       : 'javaniuniu' # GitHub repo owner
    admin: # GitHub repo owner and collaborators, only these guys can initialize GitHub issues, IT IS A LIST.
      # - your GitHub Id
       'javaniuniu'

  ## Valine
  # please refer to https://valine.js.org/en/ for more info.
  valine:
    app_id      : #wG1Y3Mr1NHwvuSoRBHSkYPnp-gzGzoHsz # LeanCloud App id
    app_key     : #dnSKoFGbwb0hhw2lOoagcXkF # LeanCloud App key
    placeholder : # Prompt information
    visitor     : # false (default)
    meta        : # "[nick, mail, link]" (default) nickname, E-mail, Personal-site


## => Pageview
##############################
pageview:
  provider: leancloud # false (default), "leancloud", "custom"

  ## Leancloud
  leancloud:
    app_id    : wG1Y3Mr1NHwvuSoRBHSkYPnp-gzGzoHsz # LeanCloud App id
    app_key   : dnSKoFGbwb0hhw2lOoagcXkF # LeanCloud App key
    app_class : javaniuniu # LeanCloud App class


## => Search
##############################
search:
  provider: default # "default" (default), false, "google", "custom"

  ## Google Custom Search Engine
  google:
    # custom_search_engine_id: 017643444788069204610:4gvhea_mvga # Google Custom Search Engine ID


## => Analytics
##############################
analytics:
  provider: custom # false (default), "google", "custom"

  ## Google Analytics
  google:
    tracking_id : # Google Analytics id for the site
    anonymize_ip: false # Anonymize IP tracking for Analytics


## => Build
##############################
markdown    : kramdown
highlighter : rouge
permalink   : date


exclude:
  - CHANGELOG.md
  - HOW_TO_RELEASE.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  # - /home
  # - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor


collections:
  docs:
    output: true
  sample_page:
    output: true
  sample_articles:
    output: true
  sample_languages:
    output: true
  language:
    output: true
  docs-python:
    output: true
  docs-java:
    output: true
  docs-cjj:
    output: true
  leetcode:
    output: true
  docker:
    output: true
  spring:
    output: true
  springboot:
    output: true
  springsecurity:
    output: true
  shiro:
    output: true
  # docs-code-design:
  #   output: true
  docs-model-design:
    output: true
  design:
    output: true
  todo:
    output: true
  docs-data:
    output: true
  # docs-data-redis:
  #   output: true
  # docs-data-jpa:
  #   output: true
  data_processing:
    output: true
  docs-util:
    output: true
  docs-annotation:
    output: true
  other:
    output: true
  java-core:
    output: true
  docs-arts:
    output: true
  docs-algo:
    output: true
  docs-other-code:
    output: true
  algo:
    output: true
  docs-skill:
    output: true
  docs-math:
    output: true
  docs-pm:
    output: true
  docs-jvm:
    output: true
  docs-mysql:
    output: true
  docs-mianshi:
    output: true
  docs-distributed:
    output: true
  docs-springcloud:
    output: true
  docs-zookeeper:
    output: true
  docs-framework:
    output: true
  docs-nacos:
    output: true

defaults:
  ## home
  - scope:
      path: "home"
    values:
      articles:
        excerpt_type: html

  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: true
      license: true
      aside:
        toc: true
      show_subscribe: true
      pageview: true

## posts
  - scope:
      path: ""
      type: posts
    values:
      layout: article # 布局类型
      sharing: true # 是否开启分享
      license: true # 该文章的许可协议
      category: post
      aside: # 设置为 true 时展示右侧边栏目录
        toc: true
      show_subscribe: true  # 是否在文章末尾显示订阅信息
      pageview: true # 是否开启阅读量统计
      lightbox: true # 该页的大图是否能点击预览
  ## samples
  - scope:
      path: ""
      type: sample_page
    values:
      nav_key: samples
  - scope:
      path: ""
      type: sample_articles
    values:
      nav_key: samples
      show_date: false
  - scope:
      path: ""
      type: sample_languages
    values:
      layout: article
      nav_key: samples
      show_date: false
  ## docs
  - scope:
      path: "_posts/en"
    values:
      layout: article
      nav_key: docs
      sidebar:
        nav: docs-en
      license: true
      aside:
        toc: true
      show_date: false
      lightbox: true
  - scope:
      path: "_posts/zh"
    values:
      layout: article
      nav_key: docs
      sidebar:
        nav: docs-zh
      license: true
      aside:
        toc: true
      lang: zh
      show_date: false
      lightbox: true
  ## todo
  - scope:
      path: "_posts/docs-todo"
    values:
      layout: article
      nav_key: docs-todo
      sidebar:
        nav: docs-todo
      license: true
      aside:
        toc: true
      show_date: true
      pageview: true
      lightbox: true
  ## docs-python
  - scope:
      path: "_posts/docs-python"
    values:
      layout: article
      nav_key: docs-python
      sidebar:
        nav: docs-python
      license: true
      aside:
        toc: true
      show_date: false
      lightbox: true
  ## docs-java
  - scope:
      path: "_posts/docs-java"
    values:
      layout: article
      nav_key: docs-java
      sidebar:
        nav: docs-java
      license: true
      aside:
        toc: true
      show_date: false
      lightbox: true
  ## docs-cjj
  - scope:
      path: "_posts/docs-cjj"
    values:
      layout: article
      nav_key: docs-cjj
      sidebar:
        nav: docs-cjj
      license: true
      aside:
        toc: true
      show_date: false
      lightbox: true
  ## leetcode
  - scope:
      path: "_posts/docs-leetcode"
    values:
      layout: article
      nav_key: leetcode
      sidebar:
        nav: docs-leetcode
      license: true
      aside:
        toc: true
      show_date: true
      pageview: true
      lightbox: true
  ## docker
  - scope:
      path: "_posts/docs-docker"
    values:
      layout: article
      nav_key: docs-docker
      sidebar:
        nav: docs-docker
      license: true
      aside:
        toc: true
      show_date: true
      pageview: true
      lightbox: true
  # spring
  - scope:
      path: "_posts/docs-spring"
    values:
      layout: article
      nav_key: docs-spring
      sidebar:
        nav: docs-spring
      license: true
      aside:
        toc: true
      show_date: true
      pageview: true
      lightbox: true
  # spring-mvc
  - scope:
      path: "_posts/docs-spring-mvc"
    values:
      layout: article
      nav_key: docs-spring-mvc
      sidebar:
        nav: docs-spring-mvc
      license: true
      aside:
        toc: true
      show_date: true
      pageview: true
      lightbox: true
      
  ## springboot
  - scope:
      path: "_posts/docs-springboot"
    values:
      layout: article
      nav_key: docs-springboot
      sidebar:
        nav: docs-springboot
      license: true
      aside:
        toc: true
      show_date: true
      pageview: true
      lightbox: true
  # springsecurity
  - scope:
      path: "_posts/docs-springsecurity"
    values:
      layout: article
      nav_key: docs-springsecurity
      sidebar:
        nav: docs-springsecurity
      license: true
      aside:
        toc: true
      show_date: true
      pageview: true
      lightbox: true
  ## shiro
  - scope:
      path: "_posts/docs-shiro"
    values:
      layout: article
      nav_key: docs-shiro
      sidebar:
        nav: docs-shiro
      license: true
      aside:
        toc: true
      show_date: true
      pageview: true
      lightbox: true
  ## docs-code-design
  # - scope:
  #     path: "_posts/java-code-design"
  #   values:
  #     layout: article
  #     nav_key: docs_code_design
  #     sidebar:
  #       nav: docs-code-design
  #     license: true
  #     aside:
  #       toc: true
  #     show_date: true
  #     pageview: true
  #     lightbox: true
  ## docs-model-design
  - scope:
      path: "_posts/docs-model-design"
    values:
      layout: article
      nav_key: docs-model-design
      sidebar:
        nav: docs-model-design
      license: true
      aside:
        toc: true
      show_date: true
      pageview: true
      lightbox: true
  # ## docs-data-redis
  # - scope:
  #     path: "_posts/java-code-redis"
  #   values:
  #     layout: article
  #     nav_key: docs-data-redis
  #     sidebar:
  #       nav: docs-data-redis
  #     license: true
  #     aside:
  #       toc: true
  #     show_date: true
  #     pageview: true
  #     lightbox: true
  ## docs-data
  - scope:
      path: "_posts/docs-data"
    values:
      layout: article
      nav_key: docs-data
      sidebar:
        nav: docs-data
      license: true
      aside:
        toc: true
      show_date: true
      pageview: true
      lightbox: true
  ## docs-annotation
  - scope:
      path: "_posts/docs-annotation"
    values:
      layout: article
      nav_key: docs-annotation
      sidebar:
        nav: docs-annotation
      license: true
      aside:
        toc: true
      show_date: true
      pageview: true
      lightbox: true
  ## docs-util
  - scope:
      path: "_posts/docs-util"
    values:
      layout: article
      nav_key: docs-util
      sidebar:
        nav: docs-util
      license: true
      aside:
        toc: true
      show_date: true
      pageview: true
      lightbox: true
  ## docs-java-core
  - scope:
      path: "_posts/docs-java-core"
    values:
      layout: article
      nav_key: docs-java-core
      sidebar:
        nav: docs-java-core
      license: true
      aside:
        toc: true
      show_date: true
      pageview: true
      lightbox: true
  ## docs-arts
  - scope:
      path: "_posts/docs-arts"
    values:
      layout: article
      nav_key: docs-arts
      sidebar:
        nav: docs-arts
      license: true
      aside:
        toc: true
      show_date: true
      pageview: true
      lightbox: true
  ## docs-algo
  - scope:
      path: "_posts/docs-algo"
    values:
      layout: article
      nav_key: docs-algo
      sidebar:
        nav: docs-algo
      license: true
      aside:
        toc: true
      show_date: true
      pageview: true
      lightbox: true
  ## docs-other-code
  - scope:
      path: "_posts/docs-other-code"
    values:
      layout: article
      nav_key: docs-other-code
      sidebar:
        nav: docs-other-code
      license: true
      aside:
        toc: true
      show_date: true
      pageview: true
      lightbox: true
  ## docs-skill
  - scope:
      path: "_posts/docs-skill"
    values:
      layout: article
      nav_key: docs-skill
      sidebar:
        nav: docs-skill
      license: true
      aside:
        toc: true
      show_date: true
      pageview: true
      lightbox: true
  ## docs-math
  - scope:
      path: "_posts/docs-math"
    values:
      layout: article
      nav_key: docs-math
      sidebar:
        nav: docs-math
      license: true
      aside:
        toc: true
      show_date: true
      pageview: true
      lightbox: true
  ## docs-pm
  - scope:
      path: "_posts/docs-pm"
    values:
      layout: article
      nav_key: docs-pm
      sidebar:
        nav: docs-pm
      license: true
      aside:
        toc: true
      show_date: true
      pageview: true
      lightbox: true

  ## docs-jvm
  - scope:
      path: "_posts/docs-jvm"
    values:
      layout: article
      nav_key: docs-jvm
      sidebar:
        nav: docs-jvm
      license: true
      aside:
        toc: true
      show_date: true
      pageview: true
      lightbox: true

  ## docs-jvm
  - scope:
      path: "_posts/docs-mysql"
    values:
      layout: article
      nav_key: docs-mysql
      sidebar:
        nav: docs-mysql
      license: true
      aside:
        toc: true
      show_date: true
      pageview: true
      lightbox: true

  ## docs-mianshi
  - scope:
      path: "_posts/docs-mianshi"
    values:
      layout: article
      nav_key: docs-mianshi
      sidebar:
        nav: docs-mianshi
      license: true
      aside:
        toc: true
      show_date: true
      pageview: true
      lightbox: true

  ## docs-distributed 分布式
  - scope:
      path: "_posts/docs-distributed"
    values:
      layout: article
      nav_key: docs-distributed
      sidebar:
        nav: docs-distributed
      license: true
      aside:
        toc: true
      show_date: true
      pageview: true
      lightbox: true

  ## docs-juc 分布式
  - scope:
      path: "_posts/docs-juc"
    values:
      layout: article
      nav_key: docs-juc
      sidebar:
        nav: docs-juc
      license: true
      aside:
        toc: true
      show_date: true
      pageview: true
      lightbox: true

  ## docs-springcloud
  - scope:
      path: "_posts/docs-springcloud"
    values:
      layout: article
      nav_key: docs-springcloud
      sidebar:
        nav: docs-springcloud
      license: true
      aside:
        toc: true
      show_date: true
      pageview: true
      lightbox: true

  ## docs-zookeeper
  - scope:
      path: "_posts/docs-zookeeper"
    values:
      layout: article
      nav_key: docs-zookeeper
      sidebar:
        nav: docs-zookeeper
      license: true
      aside:
        toc: true
      show_date: true
      pageview: true
      lightbox: true

  ## docs-framework
  - scope:
      path: "_posts/docs-framework"
    values:
      layout: article
      nav_key: docs-framework
      sidebar:
        nav: docs-framework
      license: true
      aside:
        toc: true
      show_date: true
      pageview: true
      lightbox: true

  ## docs-nacos
  - scope:
      path: "_posts/docs-nacos"
    values:
      layout: article
      nav_key: docs-nacos
      sidebar:
        nav: docs-nacos
      license: true
      aside:
        toc: true
      show_date: true
      pageview: true
      lightbox: true

## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
